[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OVIS-LDMS"
authors = [{name = "ovis-ldms", email = "ldms@sandia.gov"}]
dynamic = ["version", "description"]
